# sudo is required for Docker calls
sudo: required

# mark our language as Python
language: node_js
node_js:
  - "7"

# add dependent services
services:
  - docker

before_script:
  - npm install 

# run the tests
script:
  - ./test.sh

# if build passed, deploy 
after_success:
  - ./deploy.sh