# sudo is required for Docker calls
sudo: required

branches: 
  only:
    - master

# mark our language as Python
language: node_js

# add dependent services
services:
  - docker

env:
  - DOCKER_EMAIL=kisnandor2@yahoo.com DOCKER_USERNAME=kisnandor2 DOCKER_PASSWORD=Jozsi19542@

# main script
# for the push to work, the variables below must be set
# pushes to Heroku registry, app goes live from there
script:
  # Put testing here
  # login to Heroku registry
  - echo $DOCKER_EMAIL
  - echo $DOCKER_USERNAME
  - echo $DOCKER_PASSWORD
  