# sudo is required for Docker calls
sudo: required

# mark our language as Python
language: node_js

# add dependent services
services:
  - docker

# main script
# for the push to work, the variables below must be set
# pushes to Heroku registry, app goes live from there
script:
  - ./test.sh
  - ./deploy.sh