# sudo is required for Docker calls
sudo: required
addons:
  firefox: latest

# mark our language as Python
language: node_js
node_js:
  - "7"

# add dependent services
services:
  - docker

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - fluxbox >/dev/null 2>&1 &
  - npm install 
  - ./test_e2e.sh

# run the tests
script:
  - ./test.sh

# if build passed, deploy 
after_success:
  - ./deploy.sh