# sudo is required for Docker calls
sudo: required
# get chrome for E2E tests
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable fluxbox

language: node_js
node_js:
  - "7"

# add dependent services
services:
  - docker

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - fluxbox >/dev/null 2>&1 &

# run the tests
script:
#  - ./test_e2e.sh
#  - ./test.sh

# if build passed, deploy 
after_success:
  - ./deploy.sh